# Generated by Django 5.0.4 on 2024-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'Pending'), ('C', 'Closed'), ('R', 'Resolved'), ('NA', 'No Action')], default=None, max_length=2),
        ),
    ]
