# Generated by Django 5.0.4 on 2024-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_incident_priority_incident_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='priority',
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'O'), ('Pending', 'P'), ('Closed', 'C'), ('Resolved', 'R'), ('NA', 'NA')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subject',
            field=models.CharField(max_length=10),
        ),
    ]
