# Generated by Django 5.0.4 on 2024-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_incident_priority_alter_incident_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('Low', 'L'), ('Medium', 'M'), ('High', 'H'), ('Urgent', 'U')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
