# Generated by Django 5.0.4 on 2024-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_incident_priority_alter_incident_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('Low', 'L'), ('Medium', 'M'), ('High', 'H'), ('Urgent', 'U')], default=None, max_length=10, null=True),
        ),
    ]
