# Generated by Django 5.0.4 on 2024-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_incident_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('Low', 'L'), ('Medium', 'M'), ('High', 'H'), ('Urgent', 'U')], default='Low', max_length=10),
        ),
    ]
