# Generated by Django 5.0.4 on 2024-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_incident_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'O'), ('Pending', 'P'), ('Closed', 'C'), ('Resolved', 'R'), ('NA', 'NA')], default='Open', max_length=10),
        ),
    ]
