# Generated by Django 5.0.4 on 2024-11-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
