# Generated by Django 5.0.4 on 2024-12-27 18:19

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='updated',
        ),
        migrations.AddField(
            model_name='asset',
            name='hardware',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.DateField(default=app.models.default_warranty_date),
        ),
    ]
