# Generated by Django 6.0.6 on 2026-06-20 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_asset_updated_asset_hardware_asset_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='software',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('oem', 'OEM'), ('open_source', 'Open Source'), ('freeware', 'Freeware')], default='perpetual', max_length=20),
        ),
        migrations.AddField(
            model_name='software',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='software',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('U', 'Urgent')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'Pending'), ('C', 'Closed'), ('R', 'Resolved'), ('NA', 'NA')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_license',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='software',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='software', to=settings.AUTH_USER_MODEL),
        ),
    ]
